Update armhunt.yml

diff --git a/.github/workflows/armhunt.yml b/.github/workflows/armhunt.yml
--- a/.github/workflows/armhunt.yml
+++ b/.github/workflows/armhunt.yml
@@ -62,6 +62,12 @@ jobs:
               cat result.json
               exit 0
             fi
+            echo "==== RESULT ===="
+cat result.json || true
+
+echo "==== ERROR ===="
+cat error.log || true
+            
           done
 
           echo "No capacity available"
